package dam_A51811.filmroulette.data.remote.ai

import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject
import java.util.Properties


/**
 * Implementation of [AIAssistant] that interacts with NVIDIA's NIM API.
 *
 * @param properties Configuration properties containing the API key, model, endpoint, and other settings.
 */
class AIAssistantNIM(override val properties: Properties) : AIAssistant {

    /**
     * Retrieves the identifier of the AI system used by this assistant.
     *
     * @return The string "NIM".
     */
    override fun getSystem() = "NIM"
    override val apiKeyName  = "NIM_API_KEY"
    override var model: String = properties.getProperty("NIM_MODEL", "google/gemma-2-2b-it")

    private val endpoint: String =
        properties.getProperty("NIM_ENDPOINT", "https://integrate.api.nvidia.com/v1/chat/completions")

    /**
     * Builds an HTTP request for the NIM API using the given prompt.
     *
     * @param prompt The input text to send to the NIM model.
     * @return A configured [Request] object ready to be executed.
     */
    override fun buildRequest(prompt: String): Request {
        val messagesArray = JSONArray().put(
            JSONObject().put("role", "user").put("content", prompt)
        )

        val body = JSONObject()
            .put("model", model)
            .put("messages", messagesArray)
            .put("top_p", 0.7)

        temperature?.let { body.put("temperature", it) }
        maxTokens?.let   { body.put("max_tokens", it) }

        val builder = Request.Builder()
            .url(endpoint)
            .addHeader("Content-Type", "application/json")
            .post(body.toString().toRequestBody("application/json".toMediaTypeOrNull()))

        try { builder.addHeader("Authorization", "Bearer $apiKey") }
        catch (e: Exception) { logger.warn("No NIM API key found, proceeding without auth.") }

        return builder.build()
    }

    
    /**
     * Parses the response from the NIM API and extracts the generated content.
     *
     * @param responseBody The raw JSON response body returned by the API.
     * @return The extracted text generated by the model.
     * @throws Exception If the response cannot be parsed or the expected fields are missing.
     */
    override fun parseResponse(responseBody: String): String {
        return try {
            val json    = JSONObject(responseBody)
            val choices = json.getJSONArray("choices")
            choices.getJSONObject(0)
                .getJSONObject("message")
                .getString("content")
                .trim()
        } catch (e: JSONException) {
            logger.error("Failed to parse NIM JSON: ${e.message}")
            throw Exception("Failed to parse NIM response: ${e.message}", e)
        }
    }
}
