package dam_A51811.filmroulette.data.remote.ai

import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.Properties


/**
 * Implementation of [AIAssistant] that interacts with Google's Gemini API.
 *
 * @param properties Configuration properties containing the API key and other optional settings.
 */
class AIAssistantGemini(override val properties: Properties) : AIAssistant {

    /**
     * Retrieves the identifier of the AI system used by this assistant.
     *
     * @return The string "GEMINI".
     */
    override fun getSystem() = "GEMINI"
    override val apiKeyName  = "GEMINI_API_KEY"
    override var model       = "gemini-2.0-flash"

    /**
     * Builds an HTTP request for the Gemini API using the given prompt.
     *
     * @param prompt The input text to send to the Gemini model.
     * @return A configured [Request] object ready to be executed.
     */
    override fun buildRequest(prompt: String): Request {
        val messagesArray = JSONArray().put(
            JSONObject()
                .put("role", "user")
                .put("parts", JSONArray().put(JSONObject().put("text", prompt)))
        )

        val requestBody = JSONObject().put("contents", messagesArray)

        if (temperature != null || maxTokens != null) {
            val genConfig = JSONObject()
            temperature?.let { genConfig.put("temperature", it) }
            maxTokens?.let   { genConfig.put("maxOutputTokens", it) }
            requestBody.put("generationConfig", genConfig)
        }

        return Request.Builder()
            .url("https://generativelanguage.googleapis.com/v1/models/$model:generateContent?key=$apiKey")
            .addHeader("Content-Type", "application/json")
            .post(requestBody.toString().toRequestBody("application/json".toMediaTypeOrNull()))
            .build()
    }

    /**
     * Parses the response from the Gemini API and extracts the generated text.
     *
     * @param responseBody The raw JSON response body returned by the API.
     * @return The extracted text generated by the model.
     * @throws Exception If the response cannot be parsed or the expected fields are missing.
     */
    override fun parseResponse(responseBody: String): String {
        return try {
            val json       = JSONObject(responseBody)
            val candidates = json.getJSONArray("candidates")
            val content    = candidates.getJSONObject(0).getJSONObject("content")
            val text       = content.getJSONArray("parts").getJSONObject(0).getString("text")
            text.trim()
        } catch (e: org.json.JSONException) {
            logger.error("Failed to parse AI JSON: ${e.message}")
            throw Exception("Failed to parse AI response: ${e.message}", e)
        }
    }
}
